version: '3.7'
services:
    auth:
        build:
            context: ./auth
            target: DEV
        ports:
            - "3000:3000"

        environment: 
            - TEST=true

        env_file:
            - .env
        networks:
            - orange

networks:
    orange:
        driver: bridge